<?php

use App\Models\Country;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class ReInsertDataToCountriesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Country::truncate();

        $countries = [
            [1,'Afghanistan','AFG',93],
            [2,'Aland Islands','ALA',358],
            [3,'Albania','ALB',355],
            [4,'Algeria','DZA',213],
            [5,'American Samoa','ASM',1684],
            [6,'Andorra','AND',376],
            [7,'Angola','AGO',244],
            [8,'Anguilla','AIA',1264],
            [9,'Antarctica','ATA',672],
            [10,'Antigua and Barbuda','ATG',1268],
            [11,'Argentina','ARG',54],
            [12,'Armenia','ARM',374],
            [13,'Aruba','ABW',297],
            [14,'Australia','AUS',61],
            [15,'Austria','AUT',43],
            [16,'Azerbaijan','AZE',994],
            [17,'Bahamas','BHS',1242],
            [18,'Bahrain','BHR',973],
            [19,'Bangladesh','BGD',880],
            [20,'Barbados','BRB',1246],
            [21,'Belarus','BLR',375],
            [22,'Belgium','BEL',32],
            [23,'Belize','BLZ',501],
            [24,'Benin','BEN',229],
            [25,'Bermuda','BMU',1441],
            [26,'Bhutan','BTN',975],
            [27,'Bolivia','BOL',591],
            [28,'Bonaire, Sint Eustatius and Saba','BES',599],
            [29,'Bosnia and Herzegovina','BIH',387],
            [30,'Botswana','BWA',267],
            [31,'Bouvet Island','BVT',55],
            [32,'Brazil','BRA',55],
            [33,'British Indian Ocean Territory','IOT',246],
            [34,'Brunei Darussalam','BRN',673],
            [35,'Bulgaria','BGR',359],
            [36,'Burkina Faso','BFA',226],
            [37,'Burundi','BDI',257],
            [38,'Cambodia','KHM',855],
            [39,'Cameroon','CMR',237],
            [40,'Canada','CAN',1],
            [41,'Cape Verde','CPV',238],
            [42,'Cayman Islands','CYM',1345],
            [43,'Central African Republic','CAF',236],
            [44,'Chad','TCD',235],
            [45,'Chile','CHL',56],
            [46,'China','CHN',86],
            [47,'Christmas Island','CXR',61],
            [48,'Cocos [Keeling] Islands','CCK',672],
            [49,'Colombia','COL',57],
            [50,'Comoros','COM',269],
            [51,'Congo','COG',242],
            [52,'Congo, Democratic Republic of the Congo','COD',242],
            [53,'Cook Islands','COK',682],
            [54,'Costa Rica','CRI',506],
            [55,'Cote D\'Ivoire','CIV',225],
            [56,'Croatia','HRV',385],
            [57,'Cuba','CUB',53],
            [58,'Curacao','CUW',599],
            [59,'Cyprus','CYP',357],
            [60,'Czech Republic','CZE',420],
            [61,'Denmark','DNK',45],
            [62,'Djibouti','DJI',253],
            [63,'Dominica','DMA',1767],
            [64,'Dominican Republic','DOM',1809],
            [65,'Ecuador','ECU',593],
            [66,'Egypt','EGY',20],
            [67,'El Salvador','SLV',503],
            [68,'Equatorial Guinea','GNQ',240],
            [69,'Eritrea','ERI',291],
            [70,'Estonia','EST',372],
            [71,'Ethiopia','ETH',251],
            [72,'Falkland Islands [Malvinas]','FLK',500],
            [73,'Faroe Islands','FRO',298],
            [74,'Fiji','FJI',679],
            [75,'Finland','FIN',358],
            [76,'France','FRA',33],
            [77,'French Guiana','GUF',594],
            [78,'French Polynesia','PYF',689],
            [79,'French Southern Territories','ATF',262],
            [80,'Gabon','GAB',241],
            [81,'Gambia','GMB',220],
            [82,'Georgia','GEO',995],
            [83,'Germany','DEU',49],
            [84,'Ghana','GHA',233],
            [85,'Gibraltar','GIB',350],
            [86,'Greece','GRC',30],
            [87,'Greenland','GRL',299],
            [88,'Grenada','GRD',1473],
            [89,'Guadeloupe','GLP',590],
            [90,'Guam','GUM',1671],
            [91,'Guatemala','GTM',502],
            [92,'Guernsey','GGY',44],
            [93,'Guinea','GIN',224],
            [94,'Guinea-Bissau','GNB',245],
            [95,'Guyana','GUY',592],
            [96,'Haiti','HTI',509],
            [97,'Heard Island and Mcdonald Islands','HMD',0],
            [98,'Holy See [Vatican City State]','VAT',39],
            [99,'Honduras','HND',504],
            [100,'Hong Kong','HKG',852],
            [101,'Hungary','HUN',36],
            [102,'Iceland','ISL',354],
            [103,'India','IND',91],
            [104,'Indonesia','IDN',62],
            [105,'Iran, Islamic Republic of','IRN',98],
            [106,'Iraq','IRQ',964],
            [107,'Ireland','IRL',353],
            [108,'Isle of Man','IMN',44],
            [109,'Israel','ISR',972],
            [110,'Italy','ITA',39],
            [111,'Jamaica','JAM',1876],
            [112,'Japan','JPN',81],
            [113,'Jersey','JEY',44],
            [114,'Jordan','JOR',962],
            [115,'Kazakhstan','KAZ',7],
            [116,'Kenya','KEN',254],
            [117,'Kiribati','KIR',686],
            [118,'Korea, Democratic People\'s Republic of','PRK',850],
            [119,'Korea, Republic of','KOR',82],
            [120,'Kosovo','XKX',381],
            [121,'Kuwait','KWT',965],
            [122,'Kyrgyzstan','KGZ',996],
            [123,'Lao People\'s Democratic Republic','LAO',856],
            [124,'Latvia','LVA',371],
            [125,'Lebanon','LBN',961],
            [126,'Lesotho','LSO',266],
            [127,'Liberia','LBR',231],
            [128,'Libyan Arab Jamahiriya','LBY',218],
            [129,'Liechtenstein','LIE',423],
            [130,'Lithuania','LTU',370],
            [131,'Luxembourg','LUX',352],
            [132,'Macao','MAC',853],
            [133,'Macedonia, the Former Yugoslav Republic of','MKD',389],
            [134,'Madagascar','MDG',261],
            [135,'Malawi','MWI',265],
            [136,'Malaysia','MYS',60],
            [137,'Maldives','MDV',960],
            [138,'Mali','MLI',223],
            [139,'Malta','MLT',356],
            [140,'Marshall Islands','MHL',692],
            [141,'Martinique','MTQ',596],
            [142,'Mauritania','MRT',222],
            [143,'Mauritius','MUS',230],
            [144,'Mayotte','MYT',269],
            [145,'Mexico','MEX',52],
            [146,'Micronesia, Federated States of','FSM',691],
            [147,'Moldova, Republic of','MDA',373],
            [148,'Monaco','MCO',377],
            [149,'Mongolia','MNG',976],
            [150,'Montenegro','MNE',382],
            [151,'Montserrat','MSR',1664],
            [152,'Morocco','MAR',212],
            [153,'Mozambique','MOZ',258],
            [154,'Myanmar','MMR',95],
            [155,'Namibia','NAM',264],
            [156,'Nauru','NRU',674],
            [157,'Nepal','NPL',977],
            [158,'Netherlands','NLD',31],
            [159,'Netherlands Antilles','ANT',599],
            [160,'New Caledonia','NCL',687],
            [161,'New Zealand','NZL',64],
            [162,'Nicaragua','NIC',505],
            [163,'Niger','NER',227],
            [164,'Nigeria','NGA',234],
            [165,'Niue','NIU',683],
            [166,'Norfolk Island','NFK',672],
            [167,'Northern Mariana Islands','MNP',1670],
            [168,'Norway','NOR',47],
            [169,'Oman','OMN',968],
            [170,'Pakistan','PAK',92],
            [171,'Palau','PLW',680],
            [172,'Palestinian Territory, Occupied','PSE',970],
            [173,'Panama','PAN',507],
            [174,'Papua New Guinea','PNG',675],
            [175,'Paraguay','PRY',595],
            [176,'Peru','PER',51],
            [177,'Philippines','PHL',63],
            [178,'Pitcairn','PCN',64],
            [179,'Poland','POL',48],
            [180,'Portugal','PRT',351],
            [181,'Puerto Rico','PRI',1787],
            [182,'Qatar','QAT',974],
            [183,'Reunion','REU',262],
            [184,'Romania','ROM',40],
            [185,'Russian Federation','RUS',70],
            [186,'Rwanda','RWA',250],
            [187,'Saint Barthelemy','BLM',590],
            [188,'Saint Helena','SHN',290],
            [189,'Saint Kitts and Nevis','KNA',1869],
            [190,'Saint Lucia','LCA',1758],
            [191,'Saint Martin','MAF',590],
            [192,'Saint Pierre and Miquelon','SPM',508],
            [193,'Saint Vincent and the Grenadines','VCT',1784],
            [194,'Samoa','WSM',684],
            [195,'San Marino','SMR',378],
            [196,'Sao Tome and Principe','STP',239],
            [197,'Saudi Arabia','SAU',966],
            [198,'Senegal','SEN',221],
            [199,'Serbia','SRB',381],
            [200,'Serbia and Montenegro','SCG',381],
            [201,'Seychelles','SYC',248],
            [202,'Sierra Leone','SLE',232],
            [203,'Singapore','SGP',65],
            [204,'Sint Maarten','SXM',1],
            [205,'Slovakia','SVK',421],
            [206,'Slovenia','SVN',386],
            [207,'Solomon Islands','SLB',677],
            [208,'Somalia','SOM',252],
            [209,'South Africa','ZAF',27],
            [210,'South Georgia and the South Sandwich Islands','SGS',500],
            [211,'South Sudan','SSD',211],
            [212,'Spain','ESP',34],
            [213,'Sri Lanka','LKA',94],
            [214,'Sudan','SDN',249],
            [215,'Suriname','SUR',597],
            [216,'Svalbard and Jan Mayen','SJM',47],
            [217,'Swaziland','SWZ',268],
            [218,'Sweden','SWE',46],
            [219,'Switzerland','CHE',41],
            [220,'Syrian Arab Republic','SYR',963],
            [221,'Taiwan, Province of China','TWN',886],
            [222,'Tajikistan','TJK',992],
            [223,'Tanzania, United Republic of','TZA',255],
            [224,'Thailand','THA',66],
            [225,'Timor-Leste','TLS',670],
            [226,'Togo','TGO',228],
            [227,'Tokelau','TKL',690],
            [228,'Tonga','TON',676],
            [229,'Trinidad and Tobago','TTO',1868],
            [230,'Tunisia','TUN',216],
            [231,'Turkey','TUR',90],
            [232,'Turkmenistan','TKM',7370],
            [233,'Turks and Caicos Islands','TCA',1649],
            [234,'Tuvalu','TUV',688],
            [235,'Uganda','UGA',256],
            [236,'Ukraine','UKR',380],
            [237,'United Arab Emirates','ARE',971],
            [238,'United Kingdom','GBR',44],
            [239,'United States','USA',1],
            [240,'United States Minor Outlying Islands','UMI',1],
            [241,'Uruguay','URY',598],
            [242,'Uzbekistan','UZB',998],
            [243,'Vanuatu','VUT',678],
            [244,'Venezuela','VEN',58],
            [245,'Viet Nam','VNM',84],
            [246,'Virgin Islands, British','VGB',1284],
            [247,'Virgin Islands, U.s.','VIR',1340],
            [248,'Wallis and Futuna','WLF',681],
            [249,'Western Sahara','ESH',212],
            [250,'Yemen','YEM',967],
            [251,'Zambia','ZMB',260],
            [252,'Zimbabwe','ZWE',263]
        ];

        foreach ($countries as $country){
            DB::table('countries')
                ->insert([
                    'name' => $country[1],
                    'alpha_3_code' => $country[2],
                    'dial' => $country[3]
                ]);
        }


    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Country::truncate();

        $countries= [
            [1, 'Afghanistan'],
            [2, 'Aland Islands'],
            [3, 'Albania'],
            [4, 'Algeria'],
            [5, 'American Samoa'],
            [6, 'Andorra'],
            [7, 'Angola'],
            [8, 'Anguilla'],
            [9, 'Antarctica'],
            [10, 'Antigua and Barbuda'],
            [11, 'Argentina'],
            [12, 'Armenia'],
            [13, 'Aruba'],
            [14, 'Australia'],
            [15, 'Austria'],
            [16, 'Azerbaijan'],
            [17, 'Bahamas'],
            [18, 'Bahrain'],
            [19, 'Bangladesh'],
            [20, 'Barbados'],
            [21, 'Belarus'],
            [22, 'Belgium'],
            [23, 'Belize'],
            [24, 'Benin'],
            [25, 'Bermuda'],
            [26, 'Bhutan'],
            [27, 'Bolivia'],
            [28, 'Bonaire, Sint Eustatius and Saba'],
            [29, 'Bosnia and Herzegovina'],
            [30, 'Botswana'],
            [31, 'Bouvet Island'],
            [32, 'Brazil'],
            [33, 'British Indian Ocean Territory'],
            [34, 'Brunei Darussalam'],
            [35, 'Bulgaria'],
            [36, 'Burkina Faso'],
            [37, 'Burundi'],
            [38, 'Cambodia'],
            [39, 'Cameroon'],
            [40, 'Canada'],
            [41, 'Cape Verde'],
            [42, 'Cayman Islands'],
            [43, 'Central African Republic'],
            [44, 'Chad'],
            [45, 'Chile'],
            [46, 'China'],
            [47, 'Christmas Island'],
            [48, 'Cocos [Keeling] Islands'],
            [49, 'Colombia'],
            [50, 'Comoros'],
            [51, 'Congo'],
            [52, 'Congo, the Democratic Republic of the'],
            [53, 'Cook Islands'],
            [54, 'Costa Rica'],
            [55, 'Cote D\'Ivoire'],
            [56, 'Croatia'],
            [57, 'Cuba'],
            [58, 'Curacao'],
            [59, 'Cyprus'],
            [60, 'Czech Republic'],
            [61, 'Denmark'],
            [62, 'Djibouti'],
            [63, 'Dominica'],
            [64, 'Dominican Republic'],
            [65, 'Ecuador'],
            [66, 'Egypt'],
            [67, 'El Salvador'],
            [68, 'Equatorial Guinea'],
            [69, 'Eritrea'],
            [70, 'Estonia'],
            [71, 'Ethiopia'],
            [72, 'Falkland Islands [Malvinas]'],
            [73, 'Faroe Islands'],
            [74, 'Fiji'],
            [75, 'Finland'],
            [76, 'France'],
            [77, 'French Guiana'],
            [78, 'French Polynesia'],
            [79, 'French Southern Territories'],
            [80, 'Gabon'],
            [81, 'Gambia'],
            [82, 'Georgia'],
            [83, 'Germany'],
            [84, 'Ghana'],
            [85, 'Gibraltar'],
            [86, 'Greece'],
            [87, 'Greenland'],
            [88, 'Grenada'],
            [89, 'Guadeloupe'],
            [90, 'Guam'],
            [91, 'Guatemala'],
            [92, 'Guernsey'],
            [93, 'Guinea'],
            [94, 'Guinea-Bissau'],
            [95, 'Guyana'],
            [96, 'Haiti'],
            [97, 'Heard Island and Mcdonald Islands'],
            [98, 'Holy See [Vatican City State]'],
            [99, 'Honduras'],
            [100, 'Hong Kong'],
            [101, 'Hungary'],
            [102, 'Iceland'],
            [103, 'India'],
            [104, 'Indonesia'],
            [105, 'Iran, Islamic Republic of'],
            [106, 'Iraq'],
            [107, 'Ireland'],
            [108, 'Isle of Man'],
            [109, 'Israel'],
            [110, 'Italy'],
            [111, 'Jamaica'],
            [112, 'Japan'],
            [113, 'Jersey'],
            [114, 'Jordan'],
            [115, 'Kazakhstan'],
            [116, 'Kenya'],
            [117, 'Kiribati'],
            [118, 'Korea, Democratic People"s Republic of'],
            [119, 'Korea, Republic of'],
            [120, 'Kosovo'],
            [121, 'Kuwait'],
            [122, 'Kyrgyzstan'],
            [123, 'Lao People\'s Democratic Republic'],
            [124, 'Latvia'],
            [125, 'Lebanon'],
            [126, 'Lesotho'],
            [127, 'Liberia'],
            [128, 'Libyan Arab Jamahiriya'],
            [129, 'Liechtenstein'],
            [130, 'Lithuania'],
            [131, 'Luxembourg'],
            [132, 'Macao'],
            [133, 'Macedonia, the Former Yugoslav Republic of'],
            [134, 'Madagascar'],
            [135, 'Malawi'],
            [136, 'Malaysia'],
            [137, 'Maldives'],
            [138, 'Mali'],
            [139, 'Malta'],
            [140, 'Marshall Islands'],
            [141, 'Martinique'],
            [142, 'Mauritania'],
            [143, 'Mauritius'],
            [144, 'Mayotte'],
            [145, 'Mexico'],
            [146, 'Micronesia, Federated States of'],
            [147, 'Moldova, Republic of'],
            [148, 'Monaco'],
            [149, 'Mongolia'],
            [150, 'Montenegro'],
            [151, 'Montserrat'],
            [152, 'Morocco'],
            [153, 'Mozambique'],
            [154, 'Myanmar'],
            [155, 'Namibia'],
            [156, 'Nauru'],
            [157, 'Nepal'],
            [158, 'Netherlands'],
            [159, 'Netherlands Antilles'],
            [160, 'New Caledonia'],
            [161, 'New Zealand'],
            [162, 'Nicaragua'],
            [163, 'Niger'],
            [164, 'Nigeria'],
            [165, 'Niue'],
            [166, 'Norfolk Island'],
            [167, 'Northern Mariana Islands'],
            [168, 'Norway'],
            [169, 'Oman'],
            [170, 'Pakistan'],
            [171, 'Palau'],
            [172, 'Palestinian Territory, Occupied'],
            [173, 'Panama'],
            [174, 'Papua New Guinea'],
            [175, 'Paraguay'],
            [176, 'Peru'],
            [177, 'Philippines'],
            [178, 'Pitcairn'],
            [179, 'Poland'],
            [180, 'Portugal'],
            [181, 'Puerto Rico'],
            [182, 'Qatar'],
            [183, 'Reunion'],
            [184, 'Romania'],
            [185, 'Russian Federation'],
            [186, 'Rwanda'],
            [187, 'Saint Barthelemy'],
            [188, 'Saint Helena'],
            [189, 'Saint Kitts and Nevis'],
            [190, 'Saint Lucia'],
            [191, 'Saint Martin'],
            [192, 'Saint Pierre and Miquelon'],
            [193, 'Saint Vincent and the Grenadines'],
            [194, 'Samoa'],
            [195, 'San Marino'],
            [196, 'Sao Tome and Principe'],
            [197, 'Saudi Arabia'],
            [198, 'Senegal'],
            [199, 'Serbia'],
            [200, 'Serbia and Montenegro'],
            [201, 'Seychelles'],
            [202, 'Sierra Leone'],
            [203, 'Singapore'],
            [204, 'Sint Maarten'],
            [205, 'Slovakia'],
            [206, 'Slovenia'],
            [207, 'Solomon Islands'],
            [208, 'Somalia'],
            [209, 'South Africa'],
            [210, 'South Georgia and the South Sandwich Islands'],
            [211, 'South Sudan'],
            [212, 'Spain'],
            [213, 'Sri Lanka'],
            [214, 'Sudan'],
            [215, 'Suriname'],
            [216, 'Svalbard and Jan Mayen'],
            [217, 'Swaziland'],
            [218, 'Sweden'],
            [219, 'Switzerland'],
            [220, 'Syrian Arab Republic'],
            [221, 'Taiwan, Province of China'],
            [222, 'Tajikistan'],
            [223, 'Tanzania, United Republic of'],
            [224, 'Thailand'],
            [225, 'Timor-Leste'],
            [226, 'Togo'],
            [227, 'Tokelau'],
            [228, 'Tonga'],
            [229, 'Trinidad and Tobago'],
            [230, 'Tunisia'],
            [231, 'Turkey'],
            [232, 'Turkmenistan'],
            [233, 'Turks and Caicos Islands'],
            [234, 'Tuvalu'],
            [235, 'Uganda'],
            [236, 'Ukraine'],
            [237, 'United Arab Emirates'],
            [238, 'United Kingdom'],
            [239, 'United States'],
            [240, 'United States Minor Outlying Islands'],
            [241, 'Uruguay'],
            [242, 'Uzbekistan'],
            [243, 'Vanuatu'],
            [244, 'Venezuela'],
            [245, 'Viet Nam'],
            [246, 'Virgin Islands, British'],
            [247, 'Virgin Islands, U.s.'],
            [248, 'Wallis and Futuna'],
            [249, 'Western Sahara'],
            [250, 'Yemen'],
            [251, 'Zambia'],
            [252, 'Zimbabwe']
        ];

        foreach ($countries as $country){
            DB::table('countries')->insert(['name' => $country[1]]);
        }

    }
}
