<?php

use App\Models\Region;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class AddAlpha2CodeToRegionsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('regions', function (Blueprint $table) {
            //
            $table->string('alpha_2_code', 10)->after('name')->nullable();
        });

        $regions = array (
            'AU' =>
                array (
                    'AUSTRALIAN CAPITAL TERRITORY' => 'ACT',
                    'NEW SOUTH WALES' => 'NSW',
                    'NORTHERN TERRITORY' => 'NT',
                    'QUEENSLAND' => 'QLD',
                    'SOUTH AUSTRALIA' => 'SA',
                    'TASMANIA' => 'TAS',
                    'VICTORIA' => 'VIC',
                    'WESTERN AUSTRALIA' => 'WA',
                ),
            'CA' =>
                array (
                    'ALBERTA' => 'AB',
                    'BRITISH COLUMBIA' => 'BC',
                    'MANITOBA' => 'MB',
                    'NEW BRUNSWICK' => 'NB',
                    'NEWFOUNDLAND AND LABRADOR' => 'NL',
                    'NOVA SCOTIA' => 'NS',
                    'NORTHWEST TERRITORIES' => 'NT',
                    'NUNAVUT' => 'NU',
                    'ONTARIO' => 'ON',
                    'PRINCE EDWARD ISLAND' => 'PE',
                    'QUEBEC' => 'QC',
                    'SASKATCHEWAN' => 'SK',
                    'YUKON' => 'YT',
                ),
            'GB' =>
                array (
                    'BUCKINGHAMSHIRE TWO-TIER' => 'BKM',
                    'CAMBRIDGESHIRE TWO-TIER' => 'CAM',
                    'CUMBRIA TWO-TIER' => 'CMA',
                    'DERBYSHIRE TWO-TIER' => 'DBY',
                    'DEVON TWO-TIER' => 'DEV',
                    'DORSET TWO-TIER' => 'DOR',
                    'EAST' => 'ERW',
                    'ESSEX TWO-TIER' => 'ESS',
                    'GLOUCESTERSHIRE TWO-TIER' => 'GLS',
                    'HAMPSHIRE TWO-TIER' => 'HAM',
                    'HERTFORDSHIRE TWO-TIER' => 'HRT',
                    'KENT TWO-TIER' => 'KEN',
                    'LANCASHIRE TWO-TIER' => 'LAN',
                    'LEICESTERSHIRE TWO-TIER' => 'LEC',
                    'LINCOLNSHIRE TWO-TIER' => 'LIN',
                    'NORFOLK TWO-TIER' => 'NFK',
                    'NORTH' => 'NLK',
                    'NORTHAMPTONSHIRE TWO-TIER' => 'NTH',
                    'NOTTINGHAMSHIRE TWO-TIER' => 'NTT',
                    'OXFORDSHIRE TWO-TIER' => 'OXF',
                    'SOMERSET TWO-TIER' => 'SOM',
                    'STAFFORDSHIRE TWO-TIER' => 'STS',
                    'SUFFOLK TWO-TIER' => 'SFK',
                    'SURREY TWO-TIER' => 'SRY',
                    'WARWICKSHIRE TWO-TIER' => 'WAR',
                    'WEST' => 'WLN',
                    'WORCESTERSHIRE TWO-TIER' => 'WOR',
                    'LONDON' => 'LND',
                    'BARKING' => 'BDG',
                    'BARNET LONDON' => 'BNE',
                    'BEXLEY LONDON' => 'BEX',
                    'BRENT LONDON' => 'BEN',
                    'BROMLEY LONDON' => 'BRY',
                    'CAMDEN LONDON' => 'CMD',
                    'CROYDON LONDON' => 'CRY',
                    'EALING LONDON' => 'EAL',
                    'ENFIELD LONDON' => 'ENF',
                    'GREENWICH LONDON' => 'GRE',
                    'HACKNEY LONDON' => 'HCK',
                    'HAMMERSMITH' => 'HMF',
                    'HARINGEY LONDON' => 'HRY',
                    'HARROW LONDON' => 'HRW',
                    'HAVERING LONDON' => 'HAV',
                    'HILLINGDON LONDON' => 'HIL',
                    'HOUNSLOW LONDON' => 'HNS',
                    'ISLINGTON LONDON' => 'ISL',
                    'KENSINGTON' => 'KEC',
                    'KINGSTON' => 'KHL',
                    'LAMBETH LONDON' => 'LBH',
                    'LEWISHAM LONDON' => 'LEW',
                    'MERTON LONDON' => 'MRT',
                    'NEWHAM LONDON' => 'NWM',
                    'REDBRIDGE LONDON' => 'RDB',
                    'RICHMOND' => 'RIC',
                    'SOUTHWARK LONDON' => 'SWK',
                    'SUTTON LONDON' => 'STN',
                    'TOWER' => 'TWH',
                    'WALTHAM' => 'WFT',
                    'WANDSWORTH LONDON' => 'WND',
                    'WESTMINSTER LONDON' => 'WSM',
                    'BARNSLEY METROPOLITAN' => 'BNS',
                    'BIRMINGHAM METROPOLITAN' => 'BIR',
                    'BOLTON METROPOLITAN' => 'BOL',
                    'BRADFORD METROPOLITAN' => 'BRD',
                    'BURY METROPOLITAN' => 'BUR',
                    'CALDERDALE METROPOLITAN' => 'CLD',
                    'COVENTRY METROPOLITAN' => 'COV',
                    'DONCASTER METROPOLITAN' => 'DNC',
                    'DUDLEY METROPOLITAN' => 'DUD',
                    'GATESHEAD METROPOLITAN' => 'GAT',
                    'KIRKLEES METROPOLITAN' => 'KIR',
                    'KNOWSLEY METROPOLITAN' => 'KWL',
                    'LEEDS METROPOLITAN' => 'LDS',
                    'LIVERPOOL METROPOLITAN' => 'LIV',
                    'MANCHESTER METROPOLITAN' => 'MAN',
                    'NEWCASTLE' => 'NET',
                    'OLDHAM METROPOLITAN' => 'OLD',
                    'ROCHDALE METROPOLITAN' => 'RCH',
                    'ROTHERHAM METROPOLITAN' => 'ROT',
                    'ST.' => 'SHN',
                    'SALFORD METROPOLITAN' => 'SLF',
                    'SANDWELL METROPOLITAN' => 'SAW',
                    'SEFTON METROPOLITAN' => 'SFT',
                    'SHEFFIELD METROPOLITAN' => 'SHF',
                    'SOLIHULL METROPOLITAN' => 'SOL',
                    'SOUTH' => 'SLK',
                    'STOCKPORT METROPOLITAN' => 'SKP',
                    'SUNDERLAND METROPOLITAN' => 'SND',
                    'TAMESIDE METROPOLITAN' => 'TAM',
                    'TRAFFORD METROPOLITAN' => 'TRF',
                    'WAKEFIELD METROPOLITAN' => 'WKF',
                    'WALSALL METROPOLITAN' => 'WLL',
                    'WIGAN METROPOLITAN' => 'WGN',
                    'WIRRAL METROPOLITAN' => 'WRL',
                    'WOLVERHAMPTON METROPOLITAN' => 'WLV',
                    'BATH' => 'BAS',
                    'BEDFORD UNITARY' => 'BDF',
                    'BLACKBURN' => 'BBD',
                    'BLACKPOOL UNITARY' => 'BPL',
                    'BOURNEMOUTH' => 'BCP',
                    'BRACKNELL' => 'BRC',
                    'BRIGHTON' => 'BNH',
                    'BRISTOL' => 'BST',
                    'CENTRAL' => 'CBF',
                    'CHESHIRE' => 'CHW',
                    'CORNWALL UNITARY' => 'CON',
                    'DARLINGTON UNITARY' => 'DAL',
                    'DERBY UNITARY' => 'DER',
                    'DURHAM' => 'DUR',
                    'HALTON UNITARY' => 'HAL',
                    'HARTLEPOOL UNITARY' => 'HPL',
                    'HEREFORDSHIRE UNITARY' => 'HEF',
                    'ISLE' => 'AGY',
                    'ISLES' => 'IOS',
                    'LEICESTER UNITARY' => 'LCE',
                    'LUTON UNITARY' => 'LUT',
                    'MEDWAY UNITARY' => 'MDW',
                    'MIDDLESBROUGH UNITARY' => 'MDB',
                    'MILTON' => 'MIK',
                    'NORTHUMBERLAND UNITARY' => 'NBL',
                    'NOTTINGHAM UNITARY' => 'NGM',
                    'PETERBOROUGH UNITARY' => 'PTE',
                    'PLYMOUTH UNITARY' => 'PLY',
                    'PORTSMOUTH UNITARY' => 'POR',
                    'READING UNITARY' => 'RDG',
                    'REDCAR' => 'RCC',
                    'RUTLAND UNITARY' => 'RUT',
                    'SHROPSHIRE UNITARY' => 'SHR',
                    'SLOUGH UNITARY' => 'SLG',
                    'SOUTHAMPTON UNITARY' => 'STH',
                    'SOUTHEND-ON-SEA UNITARY' => 'SOS',
                    'STOCKTON-ON-TEES UNITARY' => 'STT',
                    'STOKE-ON-TRENT UNITARY' => 'STE',
                    'SWINDON UNITARY' => 'SWD',
                    'TELFORD' => 'TFW',
                    'THURROCK UNITARY' => 'THR',
                    'TORBAY UNITARY' => 'TOB',
                    'WARRINGTON UNITARY' => 'WRT',
                    'WILTSHIRE UNITARY' => 'WIL',
                    'WINDSOR' => 'WNM',
                    'WOKINGHAM UNITARY' => 'WOK',
                    'YORK UNITARY' => 'YOR',
                    'ANTRIM' => 'ANN',
                    'ARDS' => 'AND',
                    'ARMAGH' => 'ABC',
                    'BELFAST' => 'BFS',
                    'CAUSEWAY' => 'CCG',
                    'DERRY' => 'DRS',
                    'FERMANAGH' => 'FMO',
                    'LISBURN' => 'LBC',
                    'MID' => 'MEA',
                    'MID-ULSTER DISTRICT NIR' => 'MUL',
                    'NEWRY' => 'NMD',
                    'ABERDEEN' => 'ABE',
                    'ABERDEENSHIRE COUNCIL' => 'ABD',
                    'ANGUS COUNCIL' => 'ANS',
                    'ARGYLL' => 'AGB',
                    'CLACKMANNANSHIRE COUNCIL' => 'CLK',
                    'DUMFRIES' => 'DGY',
                    'DUNDEE' => 'DND',
                    'EDINBURGH' => 'EDH',
                    'EILEAN' => 'ELS',
                    'FALKIRK COUNCIL' => 'FAL',
                    'FIFE COUNCIL' => 'FIF',
                    'GLASGOW' => 'GLG',
                    'HIGHLAND COUNCIL' => 'HLD',
                    'INVERCLYDE COUNCIL' => 'IVC',
                    'MIDLOTHIAN COUNCIL' => 'MLN',
                    'MORAY COUNCIL' => 'MRY',
                    'ORKNEY' => 'ORK',
                    'PERTH' => 'PKN',
                    'RENFREWSHIRE COUNCIL' => 'RFW',
                    'SCOTTISH' => 'SCB',
                    'SHETLAND' => 'ZET',
                    'STIRLING COUNCIL' => 'STG',
                    'BLAENAU' => 'BGW',
                    'BRIDGEND' => 'BGE',
                    'CAERPHILLY' => 'CAY',
                    'CARDIFF' => 'CRF',
                    'CARMARTHENSHIRE' => 'CMN',
                    'CEREDIGION' => 'CGN',
                    'CONWY UNITARY' => 'CWY',
                    'DENBIGHSHIRE' => 'DEN',
                    'FLINTSHIRE' => 'FLN',
                    'GWYNEDD UNITARY' => 'GWN',
                    'MERTHYR' => 'MTY',
                    'MONMOUTHSHIRE' => 'MON',
                    'NEATH' => 'NTL',
                    'NEWPORT' => 'NWP',
                    'PEMBROKESHIRE' => 'PEM',
                    'POWYS UNITARY' => 'POW',
                    'RHONDDA' => 'RCT',
                    'SWANSEA' => 'SWA',
                    'TORFAEN' => 'TOF',
                    'VALE' => 'VGL',
                    'WREXHAM' => 'WRX',
                    'SCOTLAND' => 'SCT',
                    'NORTHERN IRELAND' => 'NIR',
                    'WALES' => 'WLS',
                ),
            'US' =>
                array (
                    'ARMED FORCES AMERICAS' => 'AA',
                    'ARMED FORCES EUROPE' => 'AE',
                    'ALASKA' => 'AK',
                    'ALABAMA' => 'AL',
                    'ARMED FORCES PACIFIC' => 'AP',
                    'ARKANSAS' => 'AR',
                    'AMERICAN SAMOA' => 'AS',
                    'ARIZONA' => 'AZ',
                    'CALIFORNIA' => 'CA',
                    'COLORADO' => 'CO',
                    'CONNECTICUT' => 'CT',
                    'DISTRICT OF COLUMBIA' => 'DC',
                    'DELAWARE' => 'DE',
                    'FLORIDA' => 'FL',
                    'FEDERATED STATES OF MICRONESIA' => 'FM',
                    'GEORGIA' => 'GA',
                    'GUAM' => 'GU',
                    'HAWAII' => 'HI',
                    'IOWA' => 'IA',
                    'IDAHO' => 'ID',
                    'ILLINOIS' => 'IL',
                    'INDIANA' => 'IN',
                    'KANSAS' => 'KS',
                    'KENTUCKY' => 'KY',
                    'LOUISIANA' => 'LA',
                    'MASSACHUSETTS' => 'MA',
                    'MARYLAND' => 'MD',
                    'MAINE' => 'ME',
                    'MARSHALL ISLANDS' => 'MH',
                    'MICHIGAN' => 'MI',
                    'MINNESOTA' => 'MN',
                    'MISSOURI' => 'MO',
                    'NORTHERN MARIANA ISLANDS' => 'MP',
                    'MISSISSIPPI' => 'MS',
                    'MONTANA' => 'MT',
                    'NORTH CAROLINA' => 'NC',
                    'NORTH DAKOTA' => 'ND',
                    'NEBRASKA' => 'NE',
                    'NEW HAMPSHIRE' => 'NH',
                    'NEW JERSEY' => 'NJ',
                    'NEW MEXICO' => 'NM',
                    'NEVADA' => 'NV',
                    'NEW YORK' => 'NY',
                    'OHIO' => 'OH',
                    'OKLAHOMA' => 'OK',
                    'OREGON' => 'OR',
                    'PENNSYLVANIA' => 'PA',
                    'PUERTO RICO' => 'PR',
                    'PALAU' => 'PW',
                    'RHODE ISLAND' => 'RI',
                    'SOUTH CAROLINA' => 'SC',
                    'SOUTH DAKOTA' => 'SD',
                    'TENNESSEE' => 'TN',
                    'TEXAS' => 'TX',
                    'U.S. MINOR OUTLYING ISLANDS' => 'UM',
                    'UTAH' => 'UT',
                    'VIRGINIA' => 'VA',
                    'VIRGIN ISLANDS' => 'VI',
                    'VERMONT' => 'VT',
                    'WASHINGTON' => 'WA',
                    'WISCONSIN' => 'WI',
                    'WEST VIRGINIA' => 'WV',
                    'WYOMING' => 'WY',
                ),
        );

        $db_regions = Region::query()
            ->select('regions.*', 'countries.alpha_2_code as country_code')
            ->join('countries', 'countries.id', '=', 'regions.country_id')
            ->get();

        foreach ($db_regions as $region) {
            try {
                $region->update(['alpha_2_code' => $regions[strtoupper($region->country_code)][strtoupper($region->name)]]);

            }catch (\Exception $exception){
                continue;
            }
        }
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('regions', function (Blueprint $table) {
            //
            $table->dropColumn('alpha_2_code');
        });
    }
}
