<?php

namespace App\Enums;

class NotificationTypeEnum
{
    const ROOKIE = 'rookie';
    const LEADER = 'leader';
    const BOTH = 'both';

    const USER_TYPE = [
        self::ROOKIE,
        self::LEADER,
        self::BOTH,
    ];

    const TYPES_TAGS = [
        'leader_login' => [],
        'leader_first_gift_to_rookie' => ['<event_at>'],
        'leader_buy_micromorgi_package' => ['<amount_micromorgi>', '<amount>', '<currency>'],
        'leader_change_gift_amount' => ['<ref_username>', '<old_amount>', '<amount>'],
        'rookie_change_gift_amount' => ['<ref_username>', '<old_amount>', '<amount>'],
        'leader_renewed_gift' => ['<ref_username>', '<amount_morgi>'],
        'rookie_renewed_gift' => ['<ref_username>', '<amount_morgi>'],
        'rookie_login' => [],
        'rookie_first_gift_from_leader' => ['<ref_username>', '<amount_morgi>'],
        'rookie_receive_micromorgi' => ['<ref_username>', '<amount_micromorgi>'],
        'verified_id_card' => [],
        'id_card_rejected' => ['<reason>'],
        'user_got_bonus' => ['<amount_micromorgi>'],
        'rookie_got_bonus' => ['<amount_morgi>'],
        'description_declined' => ['<reason>'],
        'description_approved' => [],
        'photo_declined' => ['<reason>'],
        'photo_approved' => [],
        'rookie_video_declined' => ['<reason>'],
        'rookie_video_approved' => [],
        'rookie_merch_in_elaboration' => [],
        'rookie_merch_sent' => [],
        'rookie_merch_canceled' => [],
        'rookie_rejected_payment_id_card' => [],
        'rookie_rejected_payment_no_method' => [],
        'rookie_rejected_payment_min_usd' => ['<amount>'],
        'rookie_rejected_payment_general' => [],
        'rookie_new_gift' => ['<ref_username>', '<amount_morgi>'],
        'leader_new_gift' => ['<ref_username>', '<amount_morgi>'],
        'leader_deleted_account' => [],
        'rookie_deleted_account' => [],
        'blocked_leader' => ['<amount>', '<ref_username>'],
        'rookie_blocked_leader' => ['<ref_username>'],
        'invalid_card_subscription_canceled' => ['<ref_username>'],
        'leader_canceled_subscription' => ['<ref_username>'],
        'username_changed' => [],
        'rookie_birth_date_changed' => [],
        'front_id_card_rejected' => ['<reason>'],
        'back_id_card_rejected' => ['<reason>'],
        'selfie_id_card_rejected' => ['<reason>'],
        'rookie_changed_first_name' => [],
        'rookie_changed_last_name' => [],
        'rookie_winner_lottery_info' => [],
        'user_accepted' => [],
        'user_declined' => ['<reason>'],
        'rookie_compliance_refund' => [],
        'leader_compliance_refund' => [],
        'telegram_bot' => [],
        'giveback' => ['<reason>', '<amount_micromorgi>'],
        'got_bonus_coupon' => ['<amount_morgi>'],
        'got_refunded_gift_coupon' => ['<amount_morgi>', '<ref_username>'],
        'gift_inactivity_reminder' => ['<ref_username>'],
        'gift_refunded_inactivity' => ['<ref_username>'],
        'leader_blocked_rookie' => ['<ref_username>'],
        'leader_referred_rookie' => ['<ref_username>'],
        'leader_referred_rookie_welcome' => ['<ref_username>'],
        'leader_free_subscription' => ['<ref_username>'],
        'rookie_free_subscription' => ['<ref_username>'],
        'leader_pause_connection' => ['<ref_username>'],
        'transaction_goal' => ['<ref_username>', '<amount_micromorgi>', '<goal_name>', '<goal_end_date>'],
        'converter_first_message' => [],
        'photos_approved' => [],
        'updates_rejected' => ['<reason>'],
        'rookie_goal_approved' => [],
        'rookie_goal_cancelled' => ['<reason>'],
        'rookie_goal_suspended' => ['<reason>'],
        'rookie_goal_proof_approved' => [],
        'rookie_goal_proof_declined' => ['<reason>'],
        'rookie_goal_amount_reached' => [],
        'leader_goal_completed' => [],
        'rookie_goal_activated' => []
    ];

    const TYPES_TAGS_ATTRIBUTE = [
        'leader_login' => [],
        'leader_first_gift_to_rookie' => ['event_at'],
        'leader_buy_micromorgi_package' => ['amount_micromorgi', 'amount', 'currency'],
        'leader_change_gift_amount' => ['ref_username', 'old_amount', 'amount'],
        'rookie_change_gift_amount' => ['ref_username', 'old_amount', 'amount'],
        'leader_renewed_gift' => ['ref_username', 'amount_morgi'],
        'rookie_renewed_gift' => ['ref_username', 'amount_morgi'],
        'rookie_login' => [],
        'rookie_first_gift_from_leader' => ['ref_username', 'amount_morgi'],
        'rookie_receive_micromorgi' => ['ref_username', 'amount_micromorgi'],
        'verified_id_card' => [],
        'id_card_rejected' => ['reason'],
        'user_got_bonus' => ['amount_micromorgi'],
        'rookie_got_bonus' => ['amount_morgi'],
        'description_declined' => ['reason'],
        'description_approved' => [],
        'photo_declined' => ['reason'],
        'photo_approved' => [],
        'rookie_video_declined' => ['reason'],
        'rookie_video_approved' => [],
        'rookie_merch_in_elaboration' => [],
        'rookie_merch_sent' => [],
        'rookie_merch_canceled' => [],
        'rookie_rejected_payment_id_card' => [],
        'rookie_rejected_payment_no_method' => [],
        'rookie_rejected_payment_min_usd' => ['amount'],
        'rookie_rejected_payment_general' => [],
        'rookie_new_gift' => ['ref_username', 'amount_morgi'],
        'leader_new_gift' => ['ref_username', 'amount_morgi'],
        'leader_deleted_account' => [],
        'rookie_deleted_account' => [],
        'blocked_leader' => ['amount', 'ref_username'],
        'rookie_blocked_leader' => ['ref_username'],
        'invalid_card_subscription_canceled' => ['ref_username'],
        'leader_canceled_subscription' => ['ref_username'],
        'username_changed' => ['new_username'],
        'rookie_birth_date_changed' => ['new_birth_date'],
        'front_id_card_rejected' => ['reason'],
        'back_id_card_rejected' => ['reason'],
        'selfie_id_card_rejected' => ['reason'],
        'rookie_changed_first_name' => [],
        'rookie_changed_last_name' => [],
        'rookie_winner_lottery_info' => [],
        'user_accepted' => [],
        'user_declined' => ['reason'],
        'rookie_compliance_refund' => [],
        'leader_compliance_refund' => [],
        'telegram_bot' => [],
        'giveback' => ['reason', 'amount_micromorgi'],
        'got_bonus_coupon' => ['amount_morgi'],
        'got_refunded_gift_coupon' => ['amount_morgi', 'ref_username'],
        'gift_inactivity_reminder' => ['ref_username'],
        'gift_refunded_inactivity' => ['ref_username'],
        'leader_blocked_rookie' => ['ref_username'],
        'leader_referred_rookie' => ['ref_username'],
        'leader_referred_rookie_welcome' => ['ref_username'],
        'leader_free_subscription' => ['ref_username'],
        'rookie_free_subscription' => ['ref_username'],
        'leader_pause_connection' => ['ref_username'],
        'transaction_goal' => ['ref_username', 'amount_micromorgi', 'goal_name', 'goal_end_date'],
        'converter_first_message' => [],
        'photos_approved' => [],
        'updates_rejected' => ['reason'],
        'rookie_goal_approved' => [],
        'rookie_goal_cancelled' => ['reason'],
        'rookie_goal_suspended' => ['reason'],
        'rookie_goal_proof_approved' => [],
        'rookie_goal_proof_declined' => ['reason'],
        'rookie_goal_amount_reached' => [],
        'leader_goal_completed' => [],
        'rookie_goal_activated' => []
    ];
}
